appearance:
  background_color: "#C8C8C8"
  font_color: "#FFFFFF"
  button_color: "#4682B4"
  button_hover_color: "#6495ED"
  search_bar_color: "#787878"
  search_active_color: "#646464"
  keyboard_active_color: "#696969"

  feedback_bad_color: "#FF8F8F"
  feedback_okay_color: "#debf76"
  feedback_good_color: "#8bc96f"
  feedback_great_color: "#508D69"

  font_size_large: 50
  font_size_med: 24
  font_size_small: 16

  portrait_default: false

writing:
  brush_size: 5
  brush_color: "#000000"

learning_algorithm:
  default_ease_factor: 2.5
  min_ease_factor: 1.3
  max_interval: 365
  graduation_interval: 10
  lapse_interval_factor: 0.5
  quality_threshold: 3
  new_card_limit: 20
  card_review_limit: 200