[tool.poetry]
name = "kanji-trainer"
version = "0.1.0"
description = ""
authors = ["Adam Larson <admlars2@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
