general:
  app_title: "KANJI TRAINER"
  screen_width: 800
  screen_height: 480
  fps: 60

fonts:
  font: "Noto Sans Mono CJK JP Regular.otf"

keyboard:
  layout:
    - "QWERTYUIOP"
    - "ASDFGHJKL"
    - "ZXCVBNM"
  romaji_json_path: "database/data/romaji_map.json"

database:
  word_db_path: "database/kanji.db"
  study_card_db_path: "database/study_card_db.db"
  kanjivg_folder: "database/kanjivg/"